# Generated by Django 2.2.17 on 2020-12-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hjhgfkhf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hjgjhgh', models.BigIntegerField()),
            ],
        ),
    ]
